resource_types:
- name: repo.git
  type: docker-image
  source:
    repository: foo.git

resources:
- name: repo.git
  type: git
  webhook_token: ((secret))
  source:
    uri: foo.git

jobs:
- name: public-job
  max_in_flight: 1
  plan:
  - get: repo.git
  