jobs:
- name: public-job
  max_in_flight: 1
  plan:
  - task: test-image
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello!"]
